on: [push, pull_request]

name: CI

jobs:
  test:
    name: python ${{ matrix.python-version }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2.3.4
      - name: Set environment variables
        run: |-
          echo "CONDA_ENV_FILE=ci/requirements/environment.yml" >> $GITHUB_ENV
          echo "PYTHON_VERSION=${{ matrix.python-version }}" >> $GITHUB_ENV
      - name: Cache conda
        uses: actions/cache@v2.1.6
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-py${{ matrix.python-version }}-${{
            hashFiles('ci/requirements/environment.yml') }}
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          channel-priority: strict
          miniforge-version: latest
          miniforge-variant: Mambaforge
          environment-file: ci/requirements/environment.yml
          python-version: ${{ matrix.python-version }}
          activate-environment: pygeoutils-tests
          use-mamba: true
          use-only-tar-bz2: true
      - name: Install pygeoutils
        run: |-
          mamba info -a
          mamba list
          python -m pip install --no-deps --use-feature=in-tree-build .
      - name: Version info
        run: |-
          python -c "import pygeoutils; pygeoutils.show_versions()"
      - name: Run pytest
        run: |-
          pytest
      - name: Run codecov and upload the report
        uses: codecov/codecov-action@v2.0.1
        with:
          file: ./coverage.xml
          flags: unittests
          env_vars: RUNNER_OS,PYTHON_VERSION
          name: codecov-umbrella
          fail_ci_if_error: false
